#define DICT_GLYPH_VALUES	@"AirDrop",\
							@"AirPlane",\
							@"AirPods",\
							@"Amazon",\
							@"Apple",\
							@"ApplePay",\
							@"Arcade",\
							@"Bluetooth",\
							@"Book",\
							@"Brave",\
							@"Brightness",\
							@"Cellular",\
							@"Check",\
							@"Chrome",\
							@"Cloud",\
							@"Discord",\
							@"Dropbox",\
							@"Facebook",\
							@"FaceID",\
							@"Flashlight",\
							@"Genius",\
							@"GitHub",\
							@"Heart",\
							@"HomeButton",\
							@"Instagram",\
							@"Link",\
							@"Maps",\
							@"Menu",\
							@"Message",\
							@"Messenger",\
							@"Moon",\
							@"More",\
							@"Music",\
							@"MusicSimple",\
							@"Netflix",\
							@"PayPal",\
							@"Phone",\
							@"Photo",\
							@"Podcast",\
							@"Radio",\
							@"Reboot",\
							@"Reddit",\
							@"Respring",\
							@"Restart",\
							@"Safari",\
							@"Settings",\
							@"Shrug",\
							@"Shutdown",\
							@"Skype",\
							@"Snapchat",\
							@"Soundcloud",\
							@"Spotify",\
							@"Switch",\
							@"Telegram",\
							@"TimCook",\
							@"Tinder",\
							@"TouchID",\
							@"Tune",\
							@"Twitch",\
							@"Twitter",\
							@"Watch",\
							@"WeChat",\
							@"Whatsapp",\
							@"Wifi",\
							@"Xbox",\
							@"Youtube",